# Generated by Django 6.0.5 on 2026-05-24 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome_projeto', models.CharField(max_length=255)),
                ('data_inicio', models.DateField()),
                ('data_final', models.DateField()),
                ('status', models.CharField(max_length=100)),
                ('prioridade', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'projetos',
            },
        ),
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome_tarefa', models.CharField(max_length=255)),
                ('responsavel', models.CharField(max_length=255)),
                ('data_inicio', models.DateField()),
                ('data_final', models.DateField()),
                ('concluida', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'tarefas',
            },
        ),
    ]
