# Generated by Django 5.2.14 on 2026-05-25 23:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sector', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome_projeto', models.CharField(max_length=255)),
                ('data_inicio', models.DateField()),
                ('data_final', models.DateField()),
                ('status', models.CharField(max_length=100)),
                ('prioridade', models.CharField(blank=True, max_length=50, null=True)),
                ('id_responsavel', models.ForeignKey(blank=True, db_column='id_responsavel', null=True, on_delete=django.db.models.deletion.CASCADE, to='users.users')),
                ('id_setor', models.ForeignKey(blank=True, db_column='id_setor', null=True, on_delete=django.db.models.deletion.CASCADE, to='sector.sector')),
            ],
            options={
                'db_table': 'projetos',
            },
        ),
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome_tarefa', models.CharField(max_length=255)),
                ('responsavel', models.CharField(max_length=255)),
                ('data_inicio', models.DateField()),
                ('data_final', models.DateField()),
                ('concluida', models.BooleanField(default=False)),
                ('id_projeto', models.ForeignKey(db_column='id_projeto', on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
            options={
                'db_table': 'tarefas',
            },
        ),
    ]
