# Generated by Django 5.2.14 on 2026-05-25 23:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Indicador',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('tipo', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'indicadores',
            },
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome_setor', models.CharField(max_length=255)),
                ('sigla', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'setores',
            },
        ),
        migrations.CreateModel(
            name='IndicadorValor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_registro', models.DateField()),
                ('tipo_registro', models.CharField(max_length=50)),
                ('id_indicador', models.ForeignKey(db_column='id_indicador', on_delete=django.db.models.deletion.CASCADE, to='sector.indicador')),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, to='users.users')),
            ],
            options={
                'db_table': 'indicadores_valores',
            },
        ),
        migrations.CreateModel(
            name='Oficio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('numero_oficio', models.IntegerField()),
                ('ano', models.IntegerField()),
                ('data_registro', models.DateField()),
                ('assunto', models.TextField()),
                ('id_usuario', models.ForeignKey(blank=True, db_column='id_usuario', null=True, on_delete=django.db.models.deletion.CASCADE, to='users.users')),
                ('id_setor', models.ForeignKey(blank=True, db_column='id_setor', null=True, on_delete=django.db.models.deletion.CASCADE, to='sector.sector')),
            ],
            options={
                'db_table': 'oficios',
            },
        ),
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('indicador', models.CharField(max_length=255)),
                ('data_registro', models.DateField()),
                ('id_usuario', models.ForeignKey(blank=True, db_column='id_usuario', null=True, on_delete=django.db.models.deletion.CASCADE, to='users.users')),
                ('id_setor', models.ForeignKey(blank=True, db_column='id_setor', null=True, on_delete=django.db.models.deletion.CASCADE, to='sector.sector')),
            ],
            options={
                'db_table': 'atividades',
            },
        ),
    ]
