# Generated by Django 6.0.5 on 2026-05-24 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('indicador', models.CharField(max_length=255)),
                ('data_registro', models.DateField()),
            ],
            options={
                'db_table': 'atividades',
            },
        ),
        migrations.CreateModel(
            name='Indicador',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('tipo', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'indicadores',
            },
        ),
        migrations.CreateModel(
            name='IndicadorValor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_registro', models.DateField()),
                ('tipo_registro', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'indicadores_valores',
            },
        ),
        migrations.CreateModel(
            name='Oficio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('numero_oficio', models.IntegerField()),
                ('ano', models.IntegerField()),
                ('data_registro', models.DateField()),
                ('assunto', models.TextField()),
            ],
            options={
                'db_table': 'oficios',
            },
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome_setor', models.CharField(max_length=255)),
                ('sigla', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'setores',
            },
        ),
    ]
