# Generated by Django 5.2.14 on 2026-05-26 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sector', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='oficio',
            name='local_fisico',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
