# Generated by Django 5.2.14 on 2026-05-28 00:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sector', '0002_oficio_local_fisico'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicador',
            name='id_setor',
            field=models.ForeignKey(blank=True, db_column='id_setor', null=True, on_delete=django.db.models.deletion.CASCADE, to='sector.sector'),
        ),
    ]
