# Generated by Django 5.2.14 on 2026-05-28 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sector', '0003_indicador_id_setor'),
    ]

    operations = [
        migrations.AddField(
            model_name='sector',
            name='nome_departamento',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
