# Generated by Django 6.0.5 on 2026-05-24 23:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sector', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('matricula', models.CharField(max_length=100, unique=True)),
                ('nome', models.CharField(max_length=255)),
                ('funcao', models.CharField(blank=True, max_length=255, null=True)),
                ('nivel_acesso', models.CharField(max_length=50)),
                ('senha', models.CharField(max_length=255)),
                ('id_setor', models.ForeignKey(blank=True, db_column='id_setor', null=True, on_delete=django.db.models.deletion.CASCADE, to='sector.sector')),
            ],
            options={
                'db_table': 'usuarios',
            },
        ),
    ]
