# Generated by Django 5.2.14 on 2026-05-25 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('matricula', models.CharField(max_length=100, unique=True)),
                ('nome', models.CharField(max_length=255)),
                ('funcao', models.CharField(blank=True, max_length=255, null=True)),
                ('nivel_acesso', models.CharField(max_length=50)),
                ('senha', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'usuarios',
            },
        ),
    ]
