# Generated by Django 5.2.14 on 2026-05-25 23:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sector', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='id_setor',
            field=models.ForeignKey(blank=True, db_column='id_setor', null=True, on_delete=django.db.models.deletion.CASCADE, to='sector.sector'),
        ),
    ]
