# Generated by Django 5.2.14 on 2026-05-28 00:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_users_id_setor'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResetSenhaLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data_reset', models.DateTimeField(auto_now_add=True)),
                ('id_responsavel', models.ForeignKey(db_column='id_responsavel', on_delete=django.db.models.deletion.CASCADE, related_name='resets_realizados', to='users.users')),
                ('id_usuario_alvo', models.ForeignKey(db_column='id_usuario_alvo', on_delete=django.db.models.deletion.CASCADE, related_name='resets_recebidos', to='users.users')),
            ],
            options={
                'db_table': 'log_reset_senha',
            },
        ),
    ]
